// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zhHans'

export type Locales =
	| 'zhHans'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	compat: {
		sharedReasons: {
			/**
			 * 未​在​安​全​上​下​文​中​运​行​。​需​要​ ​H​T​T​P​S​ ​或​从​本​地​回​环​访​问​。
			 */
			insecureContext: string
		}
		clipboard: {
			/**
			 * 剪​贴​板​ ​A​P​I
			 */
			name: string
			/**
			 * 剪​贴​板​ ​A​P​I​ ​(​C​l​i​p​b​o​a​r​d​ ​A​P​I​)​ ​允​许​网​页​在​用​户​授​权​后​读​写​系​统​剪​贴​板​的​内​容​。
			 */
			description: string
			/**
			 * 复​制​和​粘​贴​ ​T​T​M​L​ ​功​能​不​可​用​。
			 */
			effect: string
			/**
			 * 浏​览​器​不​支​持​剪​贴​板​相​关​的​ ​A​P​I​。​此​ ​A​P​I​ ​在​ ​C​h​r​o​m​i​u​m​ ​6​6​、​F​i​r​e​f​o​x​ ​1​2​5​、​S​a​f​a​r​i​ ​1​3​.​1​ ​或​以​上​版​本​中​支​持​。
			 */
			apiNotSupported: string
		}
		fileSystem: {
			/**
			 * 文​件​系​统​ ​A​P​I
			 */
			name: string
			/**
			 * 文​件​系​统​ ​A​P​I​ ​(​F​i​l​e​ ​S​y​s​t​e​m​ ​A​P​I​)​ ​允​许​网​页​在​用​户​授​权​后​读​写​磁​盘​上​的​文​件​，​提​供​接​近​原​生​的​文​件​操​作​能​力​。
			 */
			description: string
			/**
			 * 保​存​文​件​时​无​法​直​接​写​入​，​而​是​通​过​浏​览​器​下​载​；​自​动​保​存​不​可​用​。
			 */
			effect: string
			/**
			 * 浏​览​器​不​支​持​文​件​系​统​相​关​的​ ​A​P​I​。​此​ ​A​P​I​ ​在​ ​C​h​r​o​m​i​u​m​ ​8​6​ ​及​以​上​版​本​中​支​持​，​F​i​r​e​f​o​x​ ​和​ ​S​a​f​a​r​i​ ​暂​不​支​持​。
			 */
			apiNotSupported: string
		}
		mediaSession: {
			/**
			 * 媒​体​会​话​ ​A​P​I
			 */
			name: string
			/**
			 * 媒​体​会​话​ ​(​M​e​d​i​a​ ​S​e​s​s​i​o​n​)​ ​允​许​网​页​自​定​义​媒​体​通​知​和​响​应​媒​体​键​事​件​。
			 */
			description: string
			/**
			 * 将​不​能​从​系​统​媒​体​控​制​界​面​（​如​锁​屏​界​面​或​通​知​中​心​）​控​制​媒​体​播​放​。
			 */
			effect: string
			/**
			 * 浏​览​器​不​支​持​媒​体​会​话​相​关​的​ ​A​P​I​。​此​ ​A​P​I​ ​在​ ​C​h​r​o​m​i​u​m​ ​7​2​、​F​i​r​e​f​o​x​ ​8​2​、​S​a​f​a​r​i​ ​1​5​ ​或​以​上​版​本​中​支​持​。​F​i​r​e​f​o​x​ ​A​n​d​r​o​i​d​ ​目​前​不​支​持​。
			 */
			apiNotSupported: string
		}
		sharedArrayBuffer: {
			/**
			 * 共​享​内​存​缓​冲​区
			 */
			name: string
			/**
			 * 共​享​内​存​缓​冲​区​ ​(​S​h​a​r​e​d​ ​A​r​r​a​y​ ​B​u​f​f​e​r​)​ ​允​许​在​多​个​线​程​间​高​效​共​享​数​据​。
			 */
			description: string
			/**
			 * 频​谱​图​功​能​不​可​用​。
			 */
			effect: string
			/**
			 * 浏​览​器​不​支​持​ ​S​h​a​r​e​d​A​r​r​a​y​B​u​f​f​e​r​。​此​ ​A​P​I​ ​在​ ​C​h​r​o​m​i​u​m​ ​6​8​、​F​i​r​e​f​o​x​ ​7​9​、​S​a​f​a​r​i​ ​1​5​.​2​ ​或​以​上​版​本​中​支​持​。
			 */
			apiNotSupported: string
			/**
			 * 未​启​用​跨​源​隔​离​ ​(​C​O​O​P​/​C​O​E​P​)​。​请​联​系​部​署​方​提​供​对​应​的​ ​H​T​T​P​ ​响​应​头​，​或​调​整​构​建​选​项​以​启​用​ ​S​e​r​v​i​c​e​ ​W​o​r​k​e​r​ ​方​式​实​现​的​跨​源​隔​离​。
			 */
			coiRequired: string
			/**
			 * 未​启​用​跨​源​隔​离​ ​(​C​O​O​P​/​C​O​E​P​)​。​此​部​署​已​尝​试​通​过​ ​S​e​r​v​i​c​e​ ​W​o​r​k​e​r​ ​启​用​跨​源​隔​离​。​若​未​生​效​，​请​尝​试​刷​新​页​面​。
			 */
			coiWorkaround: string
		}
	}
	formats: {
		sharedReferences: {
			/**
			 * 维​基​百​科
			 */
			wikipedia: string
			/**
			 * 官​方​文​档
			 */
			officialDoc: string
		}
		alp: {
			/**
			 * A​M​L​L​ ​E​d​i​t​o​r​ ​工​程​文​件
			 */
			name: string
			/**
			 * A​M​L​L​ ​E​d​i​t​o​r​ ​的​项​目​文​件​格​式​，​内​嵌​音​频​文​件​和​歌​词​数​据​，​适​合​项​目​保​存​和​传​输​。
			 */
			description: string
		}
		ttml: {
			/**
			 * A​M​L​L​ ​T​T​M​L
			 */
			name: string
			/**
			 * 基​于​ ​W​3​C​ ​T​T​M​L​ ​标​准​的​歌​词​格​式​，​遵​循​ ​A​M​L​L​ ​T​T​M​L​ ​歌​词​格​式​规​范​。
			 */
			description: string
		}
		lrc: {
			/**
			 * 基​本​ ​L​R​C
			 */
			name: string
			/**
			 * 最​常​见​的​歌​词​格​式​。​支​持​以​行​时​间​戳​，​不​支​持​逐​字​时​间​戳​。​此​处​指​基​本​ ​L​R​C​ ​格​式​，​若​导​入​基​于​ ​L​R​C​ ​的​扩​展​格​式​，​请​选​择​对​应​扩​展​格​式​选​项​。
			 */
			description: string
		}
		lrcA2: {
			/**
			 * L​R​C​ ​A​2​ ​扩​展
			 */
			name: string
			/**
			 * 基​于​ ​L​R​C​ ​的​扩​展​格​式​，​支​持​行​时​间​戳​和​逐​字​时​间​戳​，​最​早​由​ ​A​2​ ​M​e​d​i​a​ ​P​l​a​y​e​r​ ​提​出​。
			 */
			description: string
		}
		yrc: {
			/**
			 * 网​易​云​逐​字
			 */
			name: string
			/**
			 * 网​易​云​音​乐​的​私​有​逐​字​歌​词​格​式​。​支​持​行​时​间​戳​和​逐​字​时​间​戳​。
			 */
			description: string
		}
		qrc: {
			/**
			 * Q​Q​ ​音​乐​逐​字
			 */
			name: string
			/**
			 * Q​Q​ ​音​乐​的​私​有​逐​字​歌​词​格​式​。​支​持​行​时​间​戳​和​逐​字​时​间​戳​。
			 */
			description: string
		}
		spl: {
			/**
			 * 椒​盐​音​乐​逐​字
			 */
			name: string
			/**
			 * 椒​盐​音​乐​的​私​有​格​式​，​基​于​ ​L​R​C​ ​扩​展​，​支​持​行​时​间​戳​和​逐​字​时​间​戳​，​并​支​持​翻​译​。​由​于​规​则​繁​杂​，​可​能​不​完​全​可​用​。
			 */
			description: string
		}
	}
}

export type TranslationFunctions = {
	compat: {
		sharedReasons: {
			/**
			 * 未在安全上下文中运行。需要 HTTPS 或从本地回环访问。
			 */
			insecureContext: () => LocalizedString
		}
		clipboard: {
			/**
			 * 剪贴板 API
			 */
			name: () => LocalizedString
			/**
			 * 剪贴板 API (Clipboard API) 允许网页在用户授权后读写系统剪贴板的内容。
			 */
			description: () => LocalizedString
			/**
			 * 复制和粘贴 TTML 功能不可用。
			 */
			effect: () => LocalizedString
			/**
			 * 浏览器不支持剪贴板相关的 API。此 API 在 Chromium 66、Firefox 125、Safari 13.1 或以上版本中支持。
			 */
			apiNotSupported: () => LocalizedString
		}
		fileSystem: {
			/**
			 * 文件系统 API
			 */
			name: () => LocalizedString
			/**
			 * 文件系统 API (File System API) 允许网页在用户授权后读写磁盘上的文件，提供接近原生的文件操作能力。
			 */
			description: () => LocalizedString
			/**
			 * 保存文件时无法直接写入，而是通过浏览器下载；自动保存不可用。
			 */
			effect: () => LocalizedString
			/**
			 * 浏览器不支持文件系统相关的 API。此 API 在 Chromium 86 及以上版本中支持，Firefox 和 Safari 暂不支持。
			 */
			apiNotSupported: () => LocalizedString
		}
		mediaSession: {
			/**
			 * 媒体会话 API
			 */
			name: () => LocalizedString
			/**
			 * 媒体会话 (Media Session) 允许网页自定义媒体通知和响应媒体键事件。
			 */
			description: () => LocalizedString
			/**
			 * 将不能从系统媒体控制界面（如锁屏界面或通知中心）控制媒体播放。
			 */
			effect: () => LocalizedString
			/**
			 * 浏览器不支持媒体会话相关的 API。此 API 在 Chromium 72、Firefox 82、Safari 15 或以上版本中支持。Firefox Android 目前不支持。
			 */
			apiNotSupported: () => LocalizedString
		}
		sharedArrayBuffer: {
			/**
			 * 共享内存缓冲区
			 */
			name: () => LocalizedString
			/**
			 * 共享内存缓冲区 (Shared Array Buffer) 允许在多个线程间高效共享数据。
			 */
			description: () => LocalizedString
			/**
			 * 频谱图功能不可用。
			 */
			effect: () => LocalizedString
			/**
			 * 浏览器不支持 SharedArrayBuffer。此 API 在 Chromium 68、Firefox 79、Safari 15.2 或以上版本中支持。
			 */
			apiNotSupported: () => LocalizedString
			/**
			 * 未启用跨源隔离 (COOP/COEP)。请联系部署方提供对应的 HTTP 响应头，或调整构建选项以启用 Service Worker 方式实现的跨源隔离。
			 */
			coiRequired: () => LocalizedString
			/**
			 * 未启用跨源隔离 (COOP/COEP)。此部署已尝试通过 Service Worker 启用跨源隔离。若未生效，请尝试刷新页面。
			 */
			coiWorkaround: () => LocalizedString
		}
	}
	formats: {
		sharedReferences: {
			/**
			 * 维基百科
			 */
			wikipedia: () => LocalizedString
			/**
			 * 官方文档
			 */
			officialDoc: () => LocalizedString
		}
		alp: {
			/**
			 * AMLL Editor 工程文件
			 */
			name: () => LocalizedString
			/**
			 * AMLL Editor 的项目文件格式，内嵌音频文件和歌词数据，适合项目保存和传输。
			 */
			description: () => LocalizedString
		}
		ttml: {
			/**
			 * AMLL TTML
			 */
			name: () => LocalizedString
			/**
			 * 基于 W3C TTML 标准的歌词格式，遵循 AMLL TTML 歌词格式规范。
			 */
			description: () => LocalizedString
		}
		lrc: {
			/**
			 * 基本 LRC
			 */
			name: () => LocalizedString
			/**
			 * 最常见的歌词格式。支持以行时间戳，不支持逐字时间戳。此处指基本 LRC 格式，若导入基于 LRC 的扩展格式，请选择对应扩展格式选项。
			 */
			description: () => LocalizedString
		}
		lrcA2: {
			/**
			 * LRC A2 扩展
			 */
			name: () => LocalizedString
			/**
			 * 基于 LRC 的扩展格式，支持行时间戳和逐字时间戳，最早由 A2 Media Player 提出。
			 */
			description: () => LocalizedString
		}
		yrc: {
			/**
			 * 网易云逐字
			 */
			name: () => LocalizedString
			/**
			 * 网易云音乐的私有逐字歌词格式。支持行时间戳和逐字时间戳。
			 */
			description: () => LocalizedString
		}
		qrc: {
			/**
			 * QQ 音乐逐字
			 */
			name: () => LocalizedString
			/**
			 * QQ 音乐的私有逐字歌词格式。支持行时间戳和逐字时间戳。
			 */
			description: () => LocalizedString
		}
		spl: {
			/**
			 * 椒盐音乐逐字
			 */
			name: () => LocalizedString
			/**
			 * 椒盐音乐的私有格式，基于 LRC 扩展，支持行时间戳和逐字时间戳，并支持翻译。由于规则繁杂，可能不完全可用。
			 */
			description: () => LocalizedString
		}
	}
}

export type Formatters = {}
