// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zhHans'

export type Locales =
	| 'zhHans'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	compat: {
		sharedReasons: {
			/**
			 * 未​在​安​全​上​下​文​中​运​行​。​需​要​ ​H​T​T​P​S​ ​或​从​本​地​回​环​访​问​。
			 */
			insecureContext: string
		}
		clipboard: {
			/**
			 * 剪​贴​板​ ​A​P​I
			 */
			name: string
			/**
			 * 剪​贴​板​ ​A​P​I​ ​(​C​l​i​p​b​o​a​r​d​ ​A​P​I​)​ ​允​许​网​页​在​用​户​授​权​后​读​写​系​统​剪​贴​板​的​内​容​。
			 */
			description: string
			/**
			 * 复​制​和​粘​贴​ ​T​T​M​L​ ​功​能​不​可​用​。
			 */
			effect: string
			/**
			 * 浏​览​器​不​支​持​剪​贴​板​相​关​的​ ​A​P​I​。​此​ ​A​P​I​ ​在​ ​C​h​r​o​m​i​u​m​ ​6​6​、​F​i​r​e​f​o​x​ ​1​2​5​、​S​a​f​a​r​i​ ​1​3​.​1​ ​或​以​上​版​本​中​支​持​。
			 */
			apiNotSupported: string
		}
		fileSystem: {
			/**
			 * 文​件​系​统​ ​A​P​I
			 */
			name: string
			/**
			 * 文​件​系​统​ ​A​P​I​ ​(​F​i​l​e​ ​S​y​s​t​e​m​ ​A​P​I​)​ ​允​许​网​页​在​用​户​授​权​后​读​写​磁​盘​上​的​文​件​，​提​供​接​近​原​生​的​文​件​操​作​能​力​。
			 */
			description: string
			/**
			 * 保​存​文​件​时​无​法​直​接​写​入​，​而​是​通​过​浏​览​器​下​载​；​自​动​保​存​不​可​用​。
			 */
			effect: string
			/**
			 * 浏​览​器​不​支​持​文​件​系​统​相​关​的​ ​A​P​I​。​此​ ​A​P​I​ ​在​ ​C​h​r​o​m​i​u​m​ ​8​6​ ​及​以​上​版​本​中​支​持​，​F​i​r​e​f​o​x​ ​和​ ​S​a​f​a​r​i​ ​暂​不​支​持​。
			 */
			apiNotSupported: string
		}
		mediaSession: {
			/**
			 * 媒​体​会​话​ ​A​P​I
			 */
			name: string
			/**
			 * 媒​体​会​话​ ​(​M​e​d​i​a​ ​S​e​s​s​i​o​n​)​ ​允​许​网​页​自​定​义​媒​体​通​知​和​响​应​媒​体​键​事​件​。
			 */
			description: string
			/**
			 * 将​不​能​从​系​统​媒​体​控​制​界​面​（​如​锁​屏​界​面​或​通​知​中​心​）​控​制​媒​体​播​放​。
			 */
			effect: string
			/**
			 * 浏​览​器​不​支​持​媒​体​会​话​相​关​的​ ​A​P​I​。​此​ ​A​P​I​ ​在​ ​C​h​r​o​m​i​u​m​ ​7​2​、​F​i​r​e​f​o​x​ ​8​2​、​S​a​f​a​r​i​ ​1​5​ ​或​以​上​版​本​中​支​持​。​F​i​r​e​f​o​x​ ​A​n​d​r​o​i​d​ ​目​前​不​支​持​。
			 */
			apiNotSupported: string
		}
		sharedArrayBuffer: {
			/**
			 * 共​享​内​存​缓​冲​区
			 */
			name: string
			/**
			 * 共​享​内​存​缓​冲​区​ ​(​S​h​a​r​e​d​ ​A​r​r​a​y​ ​B​u​f​f​e​r​)​ ​允​许​在​多​个​线​程​间​高​效​共​享​数​据​。
			 */
			description: string
			/**
			 * 频​谱​图​功​能​不​可​用​。
			 */
			effect: string
			/**
			 * 浏​览​器​不​支​持​ ​S​h​a​r​e​d​A​r​r​a​y​B​u​f​f​e​r​。​此​ ​A​P​I​ ​在​ ​C​h​r​o​m​i​u​m​ ​6​8​、​F​i​r​e​f​o​x​ ​7​9​、​S​a​f​a​r​i​ ​1​5​.​2​ ​或​以​上​版​本​中​支​持​。
			 */
			apiNotSupported: string
			/**
			 * 未​启​用​跨​源​隔​离​ ​(​C​O​O​P​/​C​O​E​P​)​。​请​联​系​部​署​方​提​供​对​应​的​ ​H​T​T​P​ ​响​应​头​，​或​调​整​构​建​选​项​以​启​用​ ​S​e​r​v​i​c​e​ ​W​o​r​k​e​r​ ​方​式​实​现​的​跨​源​隔​离​。
			 */
			coiRequired: string
			/**
			 * 未​启​用​跨​源​隔​离​ ​(​C​O​O​P​/​C​O​E​P​)​。​此​部​署​已​尝​试​通​过​ ​S​e​r​v​i​c​e​ ​W​o​r​k​e​r​ ​启​用​跨​源​隔​离​。​若​未​生​效​，​请​尝​试​刷​新​页​面​。
			 */
			coiWorkaround: string
		}
	}
	formats: {
		sharedReferences: {
			/**
			 * 维​基​百​科
			 */
			wikipedia: string
			/**
			 * 官​方​文​档
			 */
			officialDoc: string
		}
		alp: {
			/**
			 * A​M​L​L​ ​E​d​i​t​o​r​ ​工​程​文​件
			 */
			name: string
			/**
			 * A​M​L​L​ ​E​d​i​t​o​r​ ​的​项​目​文​件​格​式​，​内​嵌​音​频​文​件​和​歌​词​数​据​，​适​合​项​目​保​存​和​传​输​。
			 */
			description: string
		}
		ttml: {
			/**
			 * A​M​L​L​ ​T​T​M​L
			 */
			name: string
			/**
			 * 基​于​ ​W​3​C​ ​T​T​M​L​ ​标​准​的​歌​词​格​式​，​遵​循​ ​A​M​L​L​ ​T​T​M​L​ ​歌​词​格​式​规​范​。
			 */
			description: string
		}
		lrc: {
			/**
			 * 基​本​ ​L​R​C
			 */
			name: string
			/**
			 * 最​常​见​的​歌​词​格​式​。​支​持​以​行​时​间​戳​，​不​支​持​逐​字​时​间​戳​。​此​处​指​基​本​ ​L​R​C​ ​格​式​，​若​导​入​基​于​ ​L​R​C​ ​的​扩​展​格​式​，​请​选​择​对​应​扩​展​格​式​选​项​。
			 */
			description: string
		}
		lrcA2: {
			/**
			 * L​R​C​ ​A​2​ ​扩​展
			 */
			name: string
			/**
			 * 基​于​ ​L​R​C​ ​的​扩​展​格​式​，​支​持​行​时​间​戳​和​逐​字​时​间​戳​，​最​早​由​ ​A​2​ ​M​e​d​i​a​ ​P​l​a​y​e​r​ ​提​出​。
			 */
			description: string
		}
		yrc: {
			/**
			 * 网​易​云​逐​字
			 */
			name: string
			/**
			 * 网​易​云​音​乐​的​私​有​逐​字​歌​词​格​式​。​支​持​行​时​间​戳​和​逐​字​时​间​戳​。
			 */
			description: string
		}
		qrc: {
			/**
			 * Q​Q​ ​音​乐​逐​字
			 */
			name: string
			/**
			 * Q​Q​ ​音​乐​的​私​有​逐​字​歌​词​格​式​。​支​持​行​时​间​戳​和​逐​字​时​间​戳​。
			 */
			description: string
		}
		spl: {
			/**
			 * 椒​盐​音​乐​逐​字
			 */
			name: string
			/**
			 * 椒​盐​音​乐​的​私​有​格​式​，​基​于​ ​L​R​C​ ​扩​展​，​支​持​行​时​间​戳​和​逐​字​时​间​戳​，​并​支​持​翻​译​。​由​于​规​则​繁​杂​，​可​能​不​完​全​可​用​。
			 */
			description: string
		}
	}
	file: {
		/**
		 * 所​有​支​持​的​格​式
		 */
		allSupportedFormats: string
		/**
		 * 未​命​名
		 */
		untitled: string
		/**
		 * 成​功​加​载​文​件
		 */
		loaded: string
		failedToReadErr: {
			/**
			 * 读​取​文​件​失​败
			 */
			summary: string
			/**
			 * 不​支​持​的​文​件​类​型​：​{​0​}
			 * @param {unknown} 0
			 */
			typeNotSupported: RequiredParams<'0'>
			/**
			 * 未​提​供​文​件​句​柄
			 */
			noHandleProvided: string
			/**
			 * 无​法​获​取​提​供​的​文​件
			 */
			unableToGetFile: string
		}
		dataDropConfirm: {
			/**
			 * 您​有​未​保​存​的​工​作
			 */
			header: string
			/**
			 * 如​果​继​续​，​所​有​未​保​存​的​更​改​将​会​丢​失​。​此​操​作​不​可​撤​销​。
			 */
			message: string
			/**
			 * 继​续
			 */
			acceptLabel: string
		}
	}
	find: {
		infLoopErr: {
			/**
			 * 搜​索​失​败
			 */
			summary: string
			/**
			 * 发​生​死​循​环​。​请​前​往​反​馈​此​问​题​。
			 */
			detail: string
		}
		noResultWarn: {
			/**
			 * 找​不​到​结​果
			 */
			summary: string
			/**
			 * 在​所​选​范​围​内​文​档​为​空​。
			 */
			detailEmpty: string
			/**
			 * 全​文​搜​索​完​毕​，​未​找​到​匹​配​项​。
			 */
			detailNoMatch: string
			/**
			 * 已​到​达​文​档​末​端​，​无​匹​配​项​。​
		​启​用​循​环​搜​索​可​从​头​开​始​继​续​搜​索​。
			 */
			detailNoMatchEnd: string
		}
		replaceSuccess: {
			/**
			 * 替​换​成​功
			 */
			summary: string
			/**
			 * 共​替​换​了​ ​{​0​}​ ​处​匹​配​项​。
			 * @param {number} 0
			 */
			detail: RequiredParams<'0'>
		}
	}
	hotkey: {
		/**
		 * 按​键​绑​定
		 */
		dialogHeader: string
		/**
		 * 未​绑​定
		 */
		notBinded: string
		btns: {
			/**
			 * 添​加
			 */
			add: string
			/**
			 * 移​除
			 */
			del: string
			/**
			 * 重​置​为​默​认
			 */
			reset: string
		}
		groupTitles: {
			/**
			 * 文​件​操​作
			 */
			file: string
			/**
			 * 视​图​与​界​面
			 */
			view: string
			/**
			 * 编​辑​操​作
			 */
			editing: string
			/**
			 * 时​轴
			 */
			timing: string
			/**
			 * 音​频​控​制
			 */
			audio: string
		}
		commands: {
			/**
			 * 打​开
			 */
			open: string
			/**
			 * 保​存
			 */
			save: string
			/**
			 * 另​存​为
			 */
			saveAs: string
			/**
			 * 新​建​空​项​目
			 */
			'new': string
			/**
			 * 导​出​到​剪​贴​板
			 */
			exportToClipboard: string
			/**
			 * 从​剪​贴​板​导​入
			 */
			importFromClipboard: string
			/**
			 * 切​换​到​内​容​视​图
			 */
			switchToContent: string
			/**
			 * 切​换​到​时​轴​视​图
			 */
			switchToTiming: string
			/**
			 * 切​换​到​预​览​视​图
			 */
			switchToPreview: string
			/**
			 * 偏​好​设​置
			 */
			preferences: string
			/**
			 * 批​量​断​字
			 */
			batchSplitText: string
			/**
			 * 元​数​据
			 */
			metadata: string
			/**
			 * 批​量​时​移
			 */
			batchTimeShift: string
			/**
			 * 撤​销
			 */
			undo: string
			/**
			 * 重​做
			 */
			redo: string
			/**
			 * 书​签
			 */
			bookmark: string
			/**
			 * 查​找
			 */
			find: string
			/**
			 * 替​换
			 */
			replace: string
			/**
			 * 删​除
			 */
			'delete': string
			/**
			 * 全​选​所​有​行
			 */
			selectAllLines: string
			/**
			 * 全​选​所​有​音​节
			 */
			selectAllSyls: string
			/**
			 * 拆​分​行
			 */
			breakLine: string
			/**
			 * 设​为​对​唱​行
			 */
			duet: string
			/**
			 * 设​为​背​景​行
			 */
			background: string
			/**
			 * 上​一​行
			 */
			goPrevLine: string
			/**
			 * 上​一​音​节
			 */
			goPrevSyl: string
			/**
			 * 上​一​音​节​并​播​放
			 */
			goPrevSylnPlay: string
			/**
			 * 下​一​行
			 */
			goNextLine: string
			/**
			 * 下​一​音​节
			 */
			goNextSyl: string
			/**
			 * 下​一​音​节​并​播​放
			 */
			goNextSylnPlay: string
			/**
			 * 播​放​当​前​音​节
			 */
			playCurrSyl: string
			/**
			 * 标​记​开​始​时​间
			 */
			markBegin: string
			/**
			 * 标​记​连​缀​时​间
			 */
			markEndBegin: string
			/**
			 * 标​记​结​束​时​间
			 */
			markEnd: string
			/**
			 * 选​择​媒​体
			 */
			chooseMedia: string
			/**
			 * 快​退
			 */
			seekBackward: string
			/**
			 * 增​大​音​量
			 */
			volumeUp: string
			/**
			 * 播​放​/​暂​停​音​频
			 */
			playPauseAudio: string
			/**
			 * 快​进
			 */
			seekForward: string
			/**
			 * 减​小​音​量
			 */
			volumeDown: string
		}
		keyNames: {
			/**
			 * 空​格
			 */
			space: string
		}
	}
	syllabify: {
		engines: {
			basic: {
				/**
				 * 基​本​断​字
				 */
				name: string
				/**
				 * 对​西​文​按​词​拆​分​，​对​于​ ​C​J​K​ ​按​字​拆​分​。​若​有​自​定​义​规​则​，​将​对​拆​分​后​的​词​应​用​，​已​拆​分​的​词​不​会​合​并​。
				 */
				description: string
			}
			jaBasic: {
				/**
				 * 日​语​基​本​断​字
				 */
				name: string
				/**
				 * 针​对​日​语​拗​音​等​做​专​门​处​理​。​若​有​自​定​义​规​则​，​将​优​先​提​取​自​定​义​拆​分​，​其​余​部​分​按​规​则​拆​分​。
				 */
				description: string
			}
			prosodic: {
				/**
				 * P​r​o​s​o​d​i​c​ ​英​语​断​字
				 */
				name: string
				/**
				 * 将​ ​S​U​B​T​L​E​X​u​s​ ​作​为​语​料​，​由​ ​P​r​o​s​o​d​i​c​ ​根​据​ ​C​M​U​D​i​c​t​ ​进​行​音​节​划​分​后​，​匹​配​回​拼​写​得​到​词​典​，​高​频​词​经​人​工​校​对​。​未​命​中​的​词​将​回​退​至​ ​C​o​m​p​r​o​m​i​s​e​。
				 */
				description: string
			}
			silabeador: {
				/**
				 * S​i​l​a​b​e​a​d​o​r​ ​西​班​牙​语​断​字
				 */
				name: string
				/**
				 * 由​ ​S​i​l​a​b​e​a​d​o​r​ ​库​提​供​的​正​字​法​西​班​牙​语​音​节​划​分​，​内​置​例​外​表​。​同​时​可​容​忍​不​常​见​或​非​西​班​牙​语​变​音​符​号​与​辅​音​集​群​。
				 */
				description: string
			}
			compromise: {
				/**
				 * C​o​m​p​r​o​m​i​s​e​ ​英​语​断​字
				 */
				name: string
				/**
				 * 由​ ​C​o​m​p​r​o​m​i​s​e​ ​库​提​供​的​正​字​法​英​语​音​节​拆​分​。
				 */
				description: string
			}
			syllabifyFr: {
				/**
				 * S​y​l​l​a​b​i​f​y​-​f​r​ ​法​语​断​字
				 */
				name: string
				/**
				 * 由​ ​S​y​l​l​a​b​i​f​y​-​f​r​ ​库​提​供​的​正​字​法​法​语​语​音​节​划​分​。
				 */
				description: string
			}
			syllabify: {
				/**
				 * S​y​l​l​a​b​i​f​y​ ​俄​语​断​字
				 */
				name: string
				/**
				 * 由​ ​S​y​l​l​a​b​i​f​y​ ​库​提​供​的​正​字​法​俄​语​音​节​划​分​。
				 */
				description: string
			}
		}
	}
}

export type TranslationFunctions = {
	compat: {
		sharedReasons: {
			/**
			 * 未在安全上下文中运行。需要 HTTPS 或从本地回环访问。
			 */
			insecureContext: () => LocalizedString
		}
		clipboard: {
			/**
			 * 剪贴板 API
			 */
			name: () => LocalizedString
			/**
			 * 剪贴板 API (Clipboard API) 允许网页在用户授权后读写系统剪贴板的内容。
			 */
			description: () => LocalizedString
			/**
			 * 复制和粘贴 TTML 功能不可用。
			 */
			effect: () => LocalizedString
			/**
			 * 浏览器不支持剪贴板相关的 API。此 API 在 Chromium 66、Firefox 125、Safari 13.1 或以上版本中支持。
			 */
			apiNotSupported: () => LocalizedString
		}
		fileSystem: {
			/**
			 * 文件系统 API
			 */
			name: () => LocalizedString
			/**
			 * 文件系统 API (File System API) 允许网页在用户授权后读写磁盘上的文件，提供接近原生的文件操作能力。
			 */
			description: () => LocalizedString
			/**
			 * 保存文件时无法直接写入，而是通过浏览器下载；自动保存不可用。
			 */
			effect: () => LocalizedString
			/**
			 * 浏览器不支持文件系统相关的 API。此 API 在 Chromium 86 及以上版本中支持，Firefox 和 Safari 暂不支持。
			 */
			apiNotSupported: () => LocalizedString
		}
		mediaSession: {
			/**
			 * 媒体会话 API
			 */
			name: () => LocalizedString
			/**
			 * 媒体会话 (Media Session) 允许网页自定义媒体通知和响应媒体键事件。
			 */
			description: () => LocalizedString
			/**
			 * 将不能从系统媒体控制界面（如锁屏界面或通知中心）控制媒体播放。
			 */
			effect: () => LocalizedString
			/**
			 * 浏览器不支持媒体会话相关的 API。此 API 在 Chromium 72、Firefox 82、Safari 15 或以上版本中支持。Firefox Android 目前不支持。
			 */
			apiNotSupported: () => LocalizedString
		}
		sharedArrayBuffer: {
			/**
			 * 共享内存缓冲区
			 */
			name: () => LocalizedString
			/**
			 * 共享内存缓冲区 (Shared Array Buffer) 允许在多个线程间高效共享数据。
			 */
			description: () => LocalizedString
			/**
			 * 频谱图功能不可用。
			 */
			effect: () => LocalizedString
			/**
			 * 浏览器不支持 SharedArrayBuffer。此 API 在 Chromium 68、Firefox 79、Safari 15.2 或以上版本中支持。
			 */
			apiNotSupported: () => LocalizedString
			/**
			 * 未启用跨源隔离 (COOP/COEP)。请联系部署方提供对应的 HTTP 响应头，或调整构建选项以启用 Service Worker 方式实现的跨源隔离。
			 */
			coiRequired: () => LocalizedString
			/**
			 * 未启用跨源隔离 (COOP/COEP)。此部署已尝试通过 Service Worker 启用跨源隔离。若未生效，请尝试刷新页面。
			 */
			coiWorkaround: () => LocalizedString
		}
	}
	formats: {
		sharedReferences: {
			/**
			 * 维基百科
			 */
			wikipedia: () => LocalizedString
			/**
			 * 官方文档
			 */
			officialDoc: () => LocalizedString
		}
		alp: {
			/**
			 * AMLL Editor 工程文件
			 */
			name: () => LocalizedString
			/**
			 * AMLL Editor 的项目文件格式，内嵌音频文件和歌词数据，适合项目保存和传输。
			 */
			description: () => LocalizedString
		}
		ttml: {
			/**
			 * AMLL TTML
			 */
			name: () => LocalizedString
			/**
			 * 基于 W3C TTML 标准的歌词格式，遵循 AMLL TTML 歌词格式规范。
			 */
			description: () => LocalizedString
		}
		lrc: {
			/**
			 * 基本 LRC
			 */
			name: () => LocalizedString
			/**
			 * 最常见的歌词格式。支持以行时间戳，不支持逐字时间戳。此处指基本 LRC 格式，若导入基于 LRC 的扩展格式，请选择对应扩展格式选项。
			 */
			description: () => LocalizedString
		}
		lrcA2: {
			/**
			 * LRC A2 扩展
			 */
			name: () => LocalizedString
			/**
			 * 基于 LRC 的扩展格式，支持行时间戳和逐字时间戳，最早由 A2 Media Player 提出。
			 */
			description: () => LocalizedString
		}
		yrc: {
			/**
			 * 网易云逐字
			 */
			name: () => LocalizedString
			/**
			 * 网易云音乐的私有逐字歌词格式。支持行时间戳和逐字时间戳。
			 */
			description: () => LocalizedString
		}
		qrc: {
			/**
			 * QQ 音乐逐字
			 */
			name: () => LocalizedString
			/**
			 * QQ 音乐的私有逐字歌词格式。支持行时间戳和逐字时间戳。
			 */
			description: () => LocalizedString
		}
		spl: {
			/**
			 * 椒盐音乐逐字
			 */
			name: () => LocalizedString
			/**
			 * 椒盐音乐的私有格式，基于 LRC 扩展，支持行时间戳和逐字时间戳，并支持翻译。由于规则繁杂，可能不完全可用。
			 */
			description: () => LocalizedString
		}
	}
	file: {
		/**
		 * 所有支持的格式
		 */
		allSupportedFormats: () => LocalizedString
		/**
		 * 未命名
		 */
		untitled: () => LocalizedString
		/**
		 * 成功加载文件
		 */
		loaded: () => LocalizedString
		failedToReadErr: {
			/**
			 * 读取文件失败
			 */
			summary: () => LocalizedString
			/**
			 * 不支持的文件类型：{0}
			 */
			typeNotSupported: (arg0: unknown) => LocalizedString
			/**
			 * 未提供文件句柄
			 */
			noHandleProvided: () => LocalizedString
			/**
			 * 无法获取提供的文件
			 */
			unableToGetFile: () => LocalizedString
		}
		dataDropConfirm: {
			/**
			 * 您有未保存的工作
			 */
			header: () => LocalizedString
			/**
			 * 如果继续，所有未保存的更改将会丢失。此操作不可撤销。
			 */
			message: () => LocalizedString
			/**
			 * 继续
			 */
			acceptLabel: () => LocalizedString
		}
	}
	find: {
		infLoopErr: {
			/**
			 * 搜索失败
			 */
			summary: () => LocalizedString
			/**
			 * 发生死循环。请前往反馈此问题。
			 */
			detail: () => LocalizedString
		}
		noResultWarn: {
			/**
			 * 找不到结果
			 */
			summary: () => LocalizedString
			/**
			 * 在所选范围内文档为空。
			 */
			detailEmpty: () => LocalizedString
			/**
			 * 全文搜索完毕，未找到匹配项。
			 */
			detailNoMatch: () => LocalizedString
			/**
			 * 已到达文档末端，无匹配项。
		启用循环搜索可从头开始继续搜索。
			 */
			detailNoMatchEnd: () => LocalizedString
		}
		replaceSuccess: {
			/**
			 * 替换成功
			 */
			summary: () => LocalizedString
			/**
			 * 共替换了 {0} 处匹配项。
			 */
			detail: (arg0: number) => LocalizedString
		}
	}
	hotkey: {
		/**
		 * 按键绑定
		 */
		dialogHeader: () => LocalizedString
		/**
		 * 未绑定
		 */
		notBinded: () => LocalizedString
		btns: {
			/**
			 * 添加
			 */
			add: () => LocalizedString
			/**
			 * 移除
			 */
			del: () => LocalizedString
			/**
			 * 重置为默认
			 */
			reset: () => LocalizedString
		}
		groupTitles: {
			/**
			 * 文件操作
			 */
			file: () => LocalizedString
			/**
			 * 视图与界面
			 */
			view: () => LocalizedString
			/**
			 * 编辑操作
			 */
			editing: () => LocalizedString
			/**
			 * 时轴
			 */
			timing: () => LocalizedString
			/**
			 * 音频控制
			 */
			audio: () => LocalizedString
		}
		commands: {
			/**
			 * 打开
			 */
			open: () => LocalizedString
			/**
			 * 保存
			 */
			save: () => LocalizedString
			/**
			 * 另存为
			 */
			saveAs: () => LocalizedString
			/**
			 * 新建空项目
			 */
			'new': () => LocalizedString
			/**
			 * 导出到剪贴板
			 */
			exportToClipboard: () => LocalizedString
			/**
			 * 从剪贴板导入
			 */
			importFromClipboard: () => LocalizedString
			/**
			 * 切换到内容视图
			 */
			switchToContent: () => LocalizedString
			/**
			 * 切换到时轴视图
			 */
			switchToTiming: () => LocalizedString
			/**
			 * 切换到预览视图
			 */
			switchToPreview: () => LocalizedString
			/**
			 * 偏好设置
			 */
			preferences: () => LocalizedString
			/**
			 * 批量断字
			 */
			batchSplitText: () => LocalizedString
			/**
			 * 元数据
			 */
			metadata: () => LocalizedString
			/**
			 * 批量时移
			 */
			batchTimeShift: () => LocalizedString
			/**
			 * 撤销
			 */
			undo: () => LocalizedString
			/**
			 * 重做
			 */
			redo: () => LocalizedString
			/**
			 * 书签
			 */
			bookmark: () => LocalizedString
			/**
			 * 查找
			 */
			find: () => LocalizedString
			/**
			 * 替换
			 */
			replace: () => LocalizedString
			/**
			 * 删除
			 */
			'delete': () => LocalizedString
			/**
			 * 全选所有行
			 */
			selectAllLines: () => LocalizedString
			/**
			 * 全选所有音节
			 */
			selectAllSyls: () => LocalizedString
			/**
			 * 拆分行
			 */
			breakLine: () => LocalizedString
			/**
			 * 设为对唱行
			 */
			duet: () => LocalizedString
			/**
			 * 设为背景行
			 */
			background: () => LocalizedString
			/**
			 * 上一行
			 */
			goPrevLine: () => LocalizedString
			/**
			 * 上一音节
			 */
			goPrevSyl: () => LocalizedString
			/**
			 * 上一音节并播放
			 */
			goPrevSylnPlay: () => LocalizedString
			/**
			 * 下一行
			 */
			goNextLine: () => LocalizedString
			/**
			 * 下一音节
			 */
			goNextSyl: () => LocalizedString
			/**
			 * 下一音节并播放
			 */
			goNextSylnPlay: () => LocalizedString
			/**
			 * 播放当前音节
			 */
			playCurrSyl: () => LocalizedString
			/**
			 * 标记开始时间
			 */
			markBegin: () => LocalizedString
			/**
			 * 标记连缀时间
			 */
			markEndBegin: () => LocalizedString
			/**
			 * 标记结束时间
			 */
			markEnd: () => LocalizedString
			/**
			 * 选择媒体
			 */
			chooseMedia: () => LocalizedString
			/**
			 * 快退
			 */
			seekBackward: () => LocalizedString
			/**
			 * 增大音量
			 */
			volumeUp: () => LocalizedString
			/**
			 * 播放/暂停音频
			 */
			playPauseAudio: () => LocalizedString
			/**
			 * 快进
			 */
			seekForward: () => LocalizedString
			/**
			 * 减小音量
			 */
			volumeDown: () => LocalizedString
		}
		keyNames: {
			/**
			 * 空格
			 */
			space: () => LocalizedString
		}
	}
	syllabify: {
		engines: {
			basic: {
				/**
				 * 基本断字
				 */
				name: () => LocalizedString
				/**
				 * 对西文按词拆分，对于 CJK 按字拆分。若有自定义规则，将对拆分后的词应用，已拆分的词不会合并。
				 */
				description: () => LocalizedString
			}
			jaBasic: {
				/**
				 * 日语基本断字
				 */
				name: () => LocalizedString
				/**
				 * 针对日语拗音等做专门处理。若有自定义规则，将优先提取自定义拆分，其余部分按规则拆分。
				 */
				description: () => LocalizedString
			}
			prosodic: {
				/**
				 * Prosodic 英语断字
				 */
				name: () => LocalizedString
				/**
				 * 将 SUBTLEXus 作为语料，由 Prosodic 根据 CMUDict 进行音节划分后，匹配回拼写得到词典，高频词经人工校对。未命中的词将回退至 Compromise。
				 */
				description: () => LocalizedString
			}
			silabeador: {
				/**
				 * Silabeador 西班牙语断字
				 */
				name: () => LocalizedString
				/**
				 * 由 Silabeador 库提供的正字法西班牙语音节划分，内置例外表。同时可容忍不常见或非西班牙语变音符号与辅音集群。
				 */
				description: () => LocalizedString
			}
			compromise: {
				/**
				 * Compromise 英语断字
				 */
				name: () => LocalizedString
				/**
				 * 由 Compromise 库提供的正字法英语音节拆分。
				 */
				description: () => LocalizedString
			}
			syllabifyFr: {
				/**
				 * Syllabify-fr 法语断字
				 */
				name: () => LocalizedString
				/**
				 * 由 Syllabify-fr 库提供的正字法法语语音节划分。
				 */
				description: () => LocalizedString
			}
			syllabify: {
				/**
				 * Syllabify 俄语断字
				 */
				name: () => LocalizedString
				/**
				 * 由 Syllabify 库提供的正字法俄语音节划分。
				 */
				description: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
